//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Presentation.Impl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Presentation.Impl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string AcceptBtnTxt {
            get {
                return ResourceManager.GetString("AcceptBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta creada exitósamente..
        /// </summary>
        internal static string AccountCreationSuccessful {
            get {
                return ResourceManager.GetString("AccountCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo puedes retar a otros usuarios con estado: {0}.
        /// </summary>
        internal static string BadChosenChallengeeMessage {
            get {
                return ResourceManager.GetString("BadChosenChallengeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password no puede estar vacío.
        /// </summary>
        internal static string BadEmptyPassword {
            get {
                return ResourceManager.GetString("BadEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario no puede estar vacío.
        /// </summary>
        internal static string BadEmptyUsername {
            get {
                return ResourceManager.GetString("BadEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password y confirmación de password deben ser iguales..
        /// </summary>
        internal static string BadPasswordConfirmation {
            get {
                return ResourceManager.GetString("BadPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe ser entre 4-16 caracteres alfanuméricos, - y _.
        /// </summary>
        internal static string BadUsername {
            get {
                return ResourceManager.GetString("BadUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya ha ingresado al sistema, 
        ///no puede crear otra cuenta..
        /// </summary>
        internal static string CantCreateAccAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("CantCreateAccAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string ChallengeDialogCancelBtn {
            get {
                return ResourceManager.GetString("ChallengeDialogCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha enviado un reto.
        /// </summary>
        internal static string ChallengeDialogMessage {
            get {
                return ResourceManager.GetString("ChallengeDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reto enviado.
        /// </summary>
        internal static string ChallengeDialogTitle {
            get {
                return ResourceManager.GetString("ChallengeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea aceptar o rechazar el reto?.
        /// </summary>
        internal static string ChallengeRecvdDialogMessage {
            get {
                return ResourceManager.GetString("ChallengeRecvdDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha recibido un reto de {0}.
        /// </summary>
        internal static string ChallengeRecvdDialogSubtitle {
            get {
                return ResourceManager.GetString("ChallengeRecvdDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reto recibido.
        /// </summary>
        internal static string ChallengeRecvdDialogTitle {
            get {
                return ResourceManager.GetString("ChallengeRecvdDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no está autentificado..
        /// </summary>
        internal static string ErrorUserNotAuthentified {
            get {
                return ResourceManager.GetString("ErrorUserNotAuthentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string FindingBattleDialogButtonTxt {
            get {
                return ResourceManager.GetString("FindingBattleDialogButtonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de esperar en lo que encontramos
        ///su oponente.
        /// </summary>
        internal static string FindingBattleDialogMessage {
            get {
                return ResourceManager.GetString("FindingBattleDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando batalla.
        /// </summary>
        internal static string FindingBattleDialogTitle {
            get {
                return ResourceManager.GetString("FindingBattleDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha unido a la sala {0}.
        /// </summary>
        internal static string HasJoinedRoomSuccess {
            get {
                return ResourceManager.GetString("HasJoinedRoomSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Principal.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido unir a la sala.
        /// </summary>
        internal static string JoinRoomFail {
            get {
                return ResourceManager.GetString("JoinRoomFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya ha ingresado al sistema. Proceda a su página de Inicio..
        /// </summary>
        internal static string LoginAlreadySignedIn {
            get {
                return ResourceManager.GetString("LoginAlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha ingresado al sistema..
        /// </summary>
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string LogoutBtnText {
            get {
                return ResourceManager.GetString("LogoutBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.]{4,16}.
        /// </summary>
        internal static string PasswordRegx {
            get {
                return ResourceManager.GetString("PasswordRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a Batalla.
        /// </summary>
        internal static string PendingBattleDialogBtnText {
            get {
                return ResourceManager.GetString("PendingBattleDialogBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presione el botón para redirigirse a la batalla.
        /// </summary>
        internal static string PendingBattleDialogMessage {
            get {
                return ResourceManager.GetString("PendingBattleDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya está en una batalla.
        /// </summary>
        internal static string PendingBattleDialogSubtitle {
            get {
                return ResourceManager.GetString("PendingBattleDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batalla pendiente.
        /// </summary>
        internal static string PendingBattleDialogTitle {
            get {
                return ResourceManager.GetString("PendingBattleDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player ranking: .
        /// </summary>
        internal static string PlayerRanking {
            get {
                return ResourceManager.GetString("PlayerRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero debe entrar a un cuarto..
        /// </summary>
        internal static string PrimeroDebeEntrarAUnCuarto {
            get {
                return ResourceManager.GetString("PrimeroDebeEntrarAUnCuarto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string RejectBtnTxt {
            get {
                return ResourceManager.GetString("RejectBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salas de Juego.
        /// </summary>
        internal static string RoomsListTitle {
            get {
                return ResourceManager.GetString("RoomsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sala.
        /// </summary>
        internal static string RoomUserIdle {
            get {
                return ResourceManager.GetString("RoomUserIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugando.
        /// </summary>
        internal static string RoomUserPlaying {
            get {
                return ResourceManager.GetString("RoomUserPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando.
        /// </summary>
        internal static string RoomUserRequestedBattle {
            get {
                return ResourceManager.GetString("RoomUserRequestedBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando.
        /// </summary>
        internal static string RoomUserRequestedChallenge {
            get {
                return ResourceManager.GetString("RoomUserRequestedChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juegos perdidos: .
        /// </summary>
        internal static string TotalGamesLost {
            get {
                return ResourceManager.GetString("TotalGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juegos en total: .
        /// </summary>
        internal static string TotalGamesPlayed {
            get {
                return ResourceManager.GetString("TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juegos ganados: .
        /// </summary>
        internal static string TotalGamesWon {
            get {
                return ResourceManager.GetString("TotalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z0-9_-]{4,16}.
        /// </summary>
        internal static string UsernameRegx {
            get {
                return ResourceManager.GetString("UsernameRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido, {0}.
        /// </summary>
        internal static string WelcomeMessagePrefix {
            get {
                return ResourceManager.GetString("WelcomeMessagePrefix", resourceCulture);
            }
        }
    }
}
