//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Game.Logic.Model", "AccountCards", "Account", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Game.Logic.Model.Account), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Game.Logic.Model.Card))]
[assembly: EdmRelationshipAttribute("Game.Logic.Model", "BattleAccount", "Battle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Game.Logic.Model.Battle), "Account", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Game.Logic.Model.Account))]
[assembly: EdmRelationshipAttribute("Game.Logic.Model", "BattleAccount1", "Battle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Game.Logic.Model.Battle), "Account", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Game.Logic.Model.Account))]

#endregion

namespace Game.Logic.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    internal partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<Card> Cards
        {
            get
            {
                if ((_Cards == null))
                {
                    _Cards = base.CreateObjectSet<Card>("Cards");
                }
                return _Cards;
            }
        }
        private ObjectSet<Card> _Cards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<Battle> StoredBattles
        {
            get
            {
                if ((_StoredBattles == null))
                {
                    _StoredBattles = base.CreateObjectSet<Battle>("StoredBattles");
                }
                return _StoredBattles;
            }
        }
        private ObjectSet<Battle> _StoredBattles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<Room> Rooms
        {
            get
            {
                if ((_Rooms == null))
                {
                    _Rooms = base.CreateObjectSet<Room>("Rooms");
                }
                return _Rooms;
            }
        }
        private ObjectSet<Room> _Rooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<UserRank> UserRanks
        {
            get
            {
                if ((_UserRanks == null))
                {
                    _UserRanks = base.CreateObjectSet<UserRank>("UserRanks");
                }
                return _UserRanks;
            }
        }
        private ObjectSet<UserRank> _UserRanks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        internal void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        internal void AddToCards(Card card)
        {
            base.AddObject("Cards", card);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StoredBattles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        internal void AddToStoredBattles(Battle battle)
        {
            base.AddObject("StoredBattles", battle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        internal void AddToRooms(Room room)
        {
            base.AddObject("Rooms", room);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserRanks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        internal void AddToUserRanks(UserRank userRank)
        {
            base.AddObject("UserRanks", userRank);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Game.Logic.Model", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    internal partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        public static Account CreateAccount(global::System.Int32 id, global::System.String username)
        {
            Account account = new Account();
            account.Id = id;
            account.Username = username;
            return account;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            private set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            internal set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        internal global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ELO
        {
            get
            {
                return _ELO;
            }
            internal set
            {
                OnELOChanging(value);
                ReportPropertyChanging("ELO");
                _ELO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ELO");
                OnELOChanged();
            }
        }
        private global::System.Int32 _ELO = 1200;
        partial void OnELOChanging(global::System.Int32 value);
        partial void OnELOChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Game.Logic.Model", "AccountCards", "Card")]
        public EntityCollection<Card> Deck
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Card>("Game.Logic.Model.AccountCards", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Card>("Game.Logic.Model.AccountCards", "Card", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Game.Logic.Model", "BattleAccount", "Battle")]
        public EntityCollection<Battle> BattlesA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Battle>("Game.Logic.Model.BattleAccount", "Battle");
            }
            protected set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Battle>("Game.Logic.Model.BattleAccount", "Battle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Game.Logic.Model", "BattleAccount1", "Battle")]
        public EntityCollection<Battle> BattlesB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Battle>("Game.Logic.Model.BattleAccount1", "Battle");
            }
            protected set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Battle>("Game.Logic.Model.BattleAccount1", "Battle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Game.Logic.Model", Name="Battle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    internal partial class Battle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Battle object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="result">Initial value of the Result property.</param>
        public static Battle CreateBattle(global::System.Int32 id, global::System.Int32 result)
        {
            Battle battle = new Battle();
            battle.Id = id;
            battle.Result = result;
            return battle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            private set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Result
        {
            get
            {
                return _Result;
            }
            protected set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private global::System.Int32 _Result;
        partial void OnResultChanging(global::System.Int32 value);
        partial void OnResultChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Game.Logic.Model", "BattleAccount", "Account")]
        public Account PlayerA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount", "Account").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount", "Account").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Account> PlayerAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Account>("Game.Logic.Model.BattleAccount", "Account", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Game.Logic.Model", "BattleAccount1", "Account")]
        public Account Account
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount1", "Account").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount1", "Account").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Account> AccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("Game.Logic.Model.BattleAccount1", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Account>("Game.Logic.Model.BattleAccount1", "Account", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Game.Logic.Model", Name="Card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    internal partial class Card : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Card object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="effect">Initial value of the Effect property.</param>
        public static Card CreateCard(global::System.Int32 id, global::System.String name, CardEffect effect)
        {
            Card card = new Card();
            card.Id = id;
            card.Name = name;
            card.Effect = StructuralObject.VerifyComplexObjectIsNotNull(effect, "Effect");
            return card;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            private set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttackPoints
        {
            get
            {
                return _AttackPoints;
            }
            set
            {
                OnAttackPointsChanging(value);
                ReportPropertyChanging("AttackPoints");
                _AttackPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttackPoints");
                OnAttackPointsChanged();
            }
        }
        private global::System.Int32 _AttackPoints = 0;
        partial void OnAttackPointsChanging(global::System.Int32 value);
        partial void OnAttackPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DefensePoints
        {
            get
            {
                return _DefensePoints;
            }
            set
            {
                OnDefensePointsChanging(value);
                ReportPropertyChanging("DefensePoints");
                _DefensePoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefensePoints");
                OnDefensePointsChanged();
            }
        }
        private global::System.Int32 _DefensePoints = 0;
        partial void OnDefensePointsChanging(global::System.Int32 value);
        partial void OnDefensePointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion
        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public CardEffect Effect
        {
            get
            {
                _Effect = GetValidValue(_Effect, "Effect", false, _EffectInitialized);
                _EffectInitialized = true;
                return _Effect;
            }
            set
            {
                OnEffectChanging(value);
                ReportPropertyChanging("Effect");
                _Effect = SetValidValue(_Effect, value, "Effect");
                _EffectInitialized = true;
                ReportPropertyChanged("Effect");
                OnEffectChanged();
            }
        }
        private CardEffect _Effect;
        private bool _EffectInitialized;
        partial void OnEffectChanging(CardEffect value);
        partial void OnEffectChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Game.Logic.Model", Name="Room")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    internal partial class Room : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Room object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Room CreateRoom(global::System.Int32 id, global::System.String name)
        {
            Room room = new Room();
            room.Id = id;
            room.Name = name;
            return room;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Game.Logic.Model", Name="UserRank")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    internal partial class UserRank : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRank object.
        /// </summary>
        /// <param name="rank">Initial value of the Rank property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        public static UserRank CreateUserRank(global::System.Int64 rank, global::System.String username)
        {
            UserRank userRank = new UserRank();
            userRank.Rank = rank;
            userRank.Username = username;
            return userRank;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.Int64 _Rank;
        partial void OnRankChanging(global::System.Int64 value);
        partial void OnRankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Game.Logic.Model", Name="CardEffect")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    internal partial class CardEffect : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name = "DefaultName";
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description = "Default Effect";
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CardAttackMultiplier
        {
            get
            {
                return _CardAttackMultiplier;
            }
            set
            {
                OnCardAttackMultiplierChanging(value);
                ReportPropertyChanging("CardAttackMultiplier");
                _CardAttackMultiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardAttackMultiplier");
                OnCardAttackMultiplierChanged();
            }
        }
        private global::System.Double _CardAttackMultiplier = 1D;
        partial void OnCardAttackMultiplierChanging(global::System.Double value);
        partial void OnCardAttackMultiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardAttackChange
        {
            get
            {
                return _CardAttackChange;
            }
            set
            {
                OnCardAttackChangeChanging(value);
                ReportPropertyChanging("CardAttackChange");
                _CardAttackChange = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardAttackChange");
                OnCardAttackChangeChanged();
            }
        }
        private global::System.Int32 _CardAttackChange = 0;
        partial void OnCardAttackChangeChanging(global::System.Int32 value);
        partial void OnCardAttackChangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CardDefenseMultiplier
        {
            get
            {
                return _CardDefenseMultiplier;
            }
            set
            {
                OnCardDefenseMultiplierChanging(value);
                ReportPropertyChanging("CardDefenseMultiplier");
                _CardDefenseMultiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardDefenseMultiplier");
                OnCardDefenseMultiplierChanged();
            }
        }
        private global::System.Double _CardDefenseMultiplier = 1D;
        partial void OnCardDefenseMultiplierChanging(global::System.Double value);
        partial void OnCardDefenseMultiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardDefenseChange
        {
            get
            {
                return _CardDefenseChange;
            }
            set
            {
                OnCardDefenseChangeChanging(value);
                ReportPropertyChanging("CardDefenseChange");
                _CardDefenseChange = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardDefenseChange");
                OnCardDefenseChangeChanged();
            }
        }
        private global::System.Int32 _CardDefenseChange = 0;
        partial void OnCardDefenseChangeChanging(global::System.Int32 value);
        partial void OnCardDefenseChangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LifePointsChange
        {
            get
            {
                return _LifePointsChange;
            }
            set
            {
                OnLifePointsChangeChanging(value);
                ReportPropertyChanging("LifePointsChange");
                _LifePointsChange = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LifePointsChange");
                OnLifePointsChangeChanged();
            }
        }
        private global::System.Double _LifePointsChange = 0D;
        partial void OnLifePointsChangeChanging(global::System.Double value);
        partial void OnLifePointsChangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DisableOpponentEffect
        {
            get
            {
                return _DisableOpponentEffect;
            }
            set
            {
                OnDisableOpponentEffectChanging(value);
                ReportPropertyChanging("DisableOpponentEffect");
                _DisableOpponentEffect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisableOpponentEffect");
                OnDisableOpponentEffectChanged();
            }
        }
        private global::System.Boolean _DisableOpponentEffect = false;
        partial void OnDisableOpponentEffectChanging(global::System.Boolean value);
        partial void OnDisableOpponentEffectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Affected
        {
            get
            {
                return _Affected;
            }
            set
            {
                OnAffectedChanging(value);
                ReportPropertyChanging("Affected");
                _Affected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Affected");
                OnAffectedChanged();
            }
        }
        private global::System.Int32 _Affected = 0;
        partial void OnAffectedChanging(global::System.Int32 value);
        partial void OnAffectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EffectTiming
        {
            get
            {
                return _EffectTiming;
            }
            set
            {
                OnEffectTimingChanging(value);
                ReportPropertyChanging("EffectTiming");
                _EffectTiming = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EffectTiming");
                OnEffectTimingChanged();
            }
        }
        private global::System.Int32 _EffectTiming = 0;
        partial void OnEffectTimingChanging(global::System.Int32 value);
        partial void OnEffectTimingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ProbabilityOfEffect
        {
            get
            {
                return _ProbabilityOfEffect;
            }
            set
            {
                OnProbabilityOfEffectChanging(value);
                ReportPropertyChanging("ProbabilityOfEffect");
                _ProbabilityOfEffect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProbabilityOfEffect");
                OnProbabilityOfEffectChanged();
            }
        }
        private global::System.Double _ProbabilityOfEffect = 0D;
        partial void OnProbabilityOfEffectChanging(global::System.Double value);
        partial void OnProbabilityOfEffectChanged();

        #endregion
    }

    #endregion
    
}
